//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebBanHangASPEntities : DbContext
    {
        public WebBanHangASPEntities()
            : base("name=WebBanHangASPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Brand_0242> Brand_0242 { get; set; }
        public DbSet<Category_0242> Category_0242 { get; set; }
        public DbSet<Order_0242> Order_0242 { get; set; }
        public DbSet<Product_0242> Product_0242 { get; set; }
        public DbSet<User_0242> User_0242 { get; set; }
    }
}
